const REGISTER = "REGISTER";
const SIGNIN = "SIGNIN";
const ISAUTH = "ISAUTH";
const USERUID = "USERUID";
const CUSTOMTOKEN = "CUSTOMTOKEN";
const GETTODO = "GETTODO";
const STOREEMAIL = "STOREEMAIL";
const SIGNOUT = "SIGNOUT";

export {
  REGISTER,
  SIGNIN,
  SIGNOUT,
  ISAUTH,
  USERUID,
  CUSTOMTOKEN,
  GETTODO,
  STOREEMAIL,
};
