const REGISTER = "REGISTER";
const SIGNIN = "SIGNIN";
const ISAUTH = "ISAUTH";
const USERUID = "USERUID";
const CUSTOMTOKEN = "CUSTOMTOKEN";
const GETTODO = "GETTODO";
const STOREEMAIL = "STOREEMAIL";

export { REGISTER, SIGNIN, ISAUTH, USERUID, CUSTOMTOKEN, GETTODO, STOREEMAIL };
